/**
 * GBS Pro Nudge — free-plugin upgrade prompt for the block CSS & JS editor.
 *
 * In Spectra Pro the block-toolbar Spectra icon opens the per-block CSS & JS
 * editor plus the Global Styles manager. Layouts generated by Zip AI apply
 * custom global classes that can only be edited there, so without Pro those
 * styles are locked. This extension re-creates the toolbar icon in the free
 * plugin and, instead of the editor, opens the same docked flyout — but the
 * editor is shown as a blurred, inert preview with a frosted upgrade card on
 * top (white-label style), pointing users to the Zip AI sidebar chat.
 *
 * Rendered only when Pro is NOT active — when Pro is present it registers the
 * real toolbar button and editor, so we stand down to avoid a duplicate icon.
 *
 * @since 1.0.9
 */

import { __ } from '@wordpress/i18n';
import apiFetch from '@wordpress/api-fetch';
import { addFilter } from '@wordpress/hooks';
import { registerPlugin } from '@wordpress/plugins';
import { createHigherOrderComponent } from '@wordpress/compose';
import { createPortal, useState, useEffect } from '@wordpress/element';
import { BlockControls, InspectorControls } from '@wordpress/block-editor';
import {
	ToolbarGroup,
	ToolbarButton,
	Button,
	__experimentalToolsPanel as ToolsPanel,
	__experimentalToolsPanelItem as ToolsPanelItem,
} from '@wordpress/components';

import SpectraIcon from '../gbs-editor/components/shared/SpectraIcon.jsx';
import './style.scss';

/**
 * Up-right arrow, matching the `ArrowUpRight` glyph the dashboard upgrade
 * notice uses (force-ui isn't available in the editor build).
 *
 * @return {Element} SVG element.
 */
const ArrowUpRight = () => (
	<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
		<path d="M7 17 17 7" />
		<path d="M7 7h10v10" />
	</svg>
);

/**
 * Padlock glyph shown at the top of the upgrade notice card.
 *
 * @return {Element} SVG element.
 */
const LockIcon = () => (
	<svg width="34" height="34" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.75" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
		<rect x="4" y="10.5" width="16" height="10.5" rx="2.5" />
		<path d="M8 10.5V7a4 4 0 0 1 8 0v3.5" />
	</svg>
);

// Spectra Pro pricing page — fallback when PHP-localized data is unavailable.
const FALLBACK_UPGRADE_URL =
	'https://wpspectra.com/pricing/?utm_source=spectra-blocks&utm_medium=editor&utm_campaign=gbs-css-js-nudge';

/**
 * Spectra Pro install/activation state, localized by the ExtensionManager and
 * mirroring the dashboard white-label logic:
 *   - `active`        → Pro is running; the free nudge stands down.
 *   - `installed`     → Pro is present but inactive; offer "Activate".
 *   - `not_installed` → Pro is absent; offer "Upgrade".
 *
 * Falls back to inferring active-ness from Pro's editor global if the localized
 * data is missing for any reason.
 *
 * @return {{state: string, upgradeUrl: string, activateUrl: string}} Pro state.
 */
const getProState = () => {
	const data = window.spectra_blocks_pro_nudge;
	if ( data && data.state ) {
		return data;
	}
	return {
		state:
			'undefined' === typeof window.spectra_blocks_pro_info
				? 'not_installed'
				: 'active',
		upgradeUrl: FALLBACK_UPGRADE_URL,
		activatePlugin: 'spectra-blocks-pro/spectra-blocks-pro',
	};
};

/**
 * Whether Pro is active — the one case where the free nudge must NOT render
 * (Pro registers the real toolbar button and editor).
 *
 * @return {boolean} True when Pro is active.
 */
const isProActive = () => 'active' === getProState().state;

/**
 * Upgrade / Activate CTA, matching the dashboard white-label logic.
 *
 * When Pro is installed-but-inactive, the button activates it through the
 * plugins REST endpoint and reloads so the real Pro editor takes over — rather
 * than sending the user off to the Plugins screen. When Pro is absent it links
 * to pricing.
 *
 * @param {Object} props           Component props.
 * @param {string} props.className CSS class for the button/link.
 * @return {Element} The CTA element.
 */
const UpgradeCta = ( { className } ) => {
	const { state, upgradeUrl, activatePlugin } = getProState();
	const [ activating, setActivating ] = useState( false );

	if ( 'installed' === state ) {
		const activate = () => {
			if ( activating ) {
				return;
			}
			setActivating( true );
			apiFetch( {
				path: `/wp/v2/plugins/${ activatePlugin }`,
				method: 'POST',
				data: { status: 'active' },
			} )
				.then( () => {
					// Activation requires a reload to load Pro's assets. Suppress the
					// editor's unsaved-changes prompt for this intentional reload by
					// stopping the editor's beforeunload handler (a capture-phase
					// listener runs first and halts it) before navigating.
					window.addEventListener(
						'beforeunload',
						( event ) => event.stopImmediatePropagation(),
						{ capture: true }
					);
					window.location.reload();
				} )
				.catch( () => setActivating( false ) );
		};

		return (
			<button
				type="button"
				className={ className }
				onClick={ activate }
				disabled={ activating }
			>
				{ activating
					? __( 'Activating…', 'spectra-blocks' )
					: __( 'Activate Now', 'spectra-blocks' ) }
			</button>
		);
	}

	return (
		<a
			className={ className }
			href={ upgradeUrl || FALLBACK_UPGRADE_URL }
			target="_blank"
			rel="noopener noreferrer"
		>
			{ __( 'Upgrade Now', 'spectra-blocks' ) }
			<ArrowUpRight />
		</a>
	);
};

/**
 * Blocks that carry the Spectra icon: every Spectra block plus the two core
 * blocks the GBS editor supports.
 *
 * @param {string} name Block name.
 * @return {boolean} True when the block should show the nudge icon.
 */
const isSupportedBlock = ( name ) =>
	'string' === typeof name &&
	( name.startsWith( 'spectra/' ) ||
		'core/image' === name ||
		'core/heading' === name );

// ─── Nudge singleton ────────────────────────────────────────────────────────────
// One host renders whichever variant is active:
//   'flyout' → toolbar "Block CSS & JS" → docked CSS/JS editor preview.
//   'modal'  → inspector "Manage Global Styles" → centered GBS manager popup.
let _nudgeVariant = null;
const _listeners = new Set();
const notify = () => _listeners.forEach( ( fn ) => fn( _nudgeVariant ) );

const nudgeSingleton = {
	openFlyout: () => {
		_nudgeVariant = 'flyout';
		notify();
	},
	toggleFlyout: () => {
		_nudgeVariant = 'flyout' === _nudgeVariant ? null : 'flyout';
		notify();
	},
	openModal: () => {
		_nudgeVariant = 'modal';
		notify();
	},
	close: () => {
		_nudgeVariant = null;
		notify();
	},
	subscribe: ( fn ) => {
		_listeners.add( fn );
		return () => _listeners.delete( fn );
	},
};

// Left-nav groups mirroring the Pro GBS manager (inert preview labels).
const NAV_GROUPS = [
	{ group: __( 'Design System', 'spectra-blocks' ), items: [ { label: __( 'Style Guide', 'spectra-blocks' ), active: true } ] },
	{ group: __( 'Styles', 'spectra-blocks' ), items: [
		{ label: __( 'CSS variables', 'spectra-blocks' ) },
		{ label: __( 'Classes & CSS', 'spectra-blocks' ) },
		{ label: __( 'Keyframes', 'spectra-blocks' ) },
	] },
	{ group: __( 'Reference', 'spectra-blocks' ), items: [
		{ label: __( 'Block defaults', 'spectra-blocks' ) },
		{ label: __( 'Token browser', 'spectra-blocks' ) },
		{ label: __( 'Cheat sheet', 'spectra-blocks' ) },
	] },
];

const PALETTE = [ '#6135ff', '#8b5cf6', '#ec4899', '#111827', '#374151', '#6b7280', '#9ca3af', '#e5e7eb' ];

/**
 * Inert, decorative replica of the Pro "Manage Global Styles" manager (left nav
 * + Style Guide view). Shown blurred behind the upgrade card so users see what
 * Pro unlocks. Purely visual — aria-hidden, no interactions.
 *
 * @return {Element} The faux GBS manager shell.
 */
const GBSManagerPreview = () => (
	<div className="spectra-gbs-nudge-modal__shell" aria-hidden="true">
		<nav className="spectra-gbs-nudge-modal__nav">
			{ NAV_GROUPS.map( ( g ) => (
				<div className="spectra-gbs-nudge-modal__navgroup" key={ g.group }>
					<p className="spectra-gbs-nudge-modal__navlabel">{ g.group }</p>
					{ g.items.map( ( it ) => (
						<span
							key={ it.label }
							className={ `spectra-gbs-nudge-modal__navitem${ it.active ? ' is-active' : '' }` }
						>
							{ it.label }
						</span>
					) ) }
				</div>
			) ) }
		</nav>
		<section className="spectra-gbs-nudge-modal__view">
			<h2 className="spectra-gbs-nudge-modal__viewtitle">{ __( 'Style Guide', 'spectra-blocks' ) }</h2>

			<h3 className="spectra-gbs-nudge-modal__sublabel">{ __( 'Palette', 'spectra-blocks' ) }</h3>
			<div className="spectra-gbs-nudge-modal__swatches">
				{ PALETTE.map( ( c, i ) => (
					<span key={ i } className="spectra-gbs-nudge-modal__swatch" style={ { background: c } } />
				) ) }
			</div>

			<h3 className="spectra-gbs-nudge-modal__sublabel">{ __( 'Typography', 'spectra-blocks' ) }</h3>
			<div className="spectra-gbs-nudge-modal__type">
				<span className="spectra-gbs-nudge-modal__type-h1">Aa { __( 'Heading', 'spectra-blocks' ) }</span>
				<span className="spectra-gbs-nudge-modal__type-h2">Aa { __( 'Subheading', 'spectra-blocks' ) }</span>
				<span className="spectra-gbs-nudge-modal__type-body">Aa { __( 'Body text', 'spectra-blocks' ) }</span>
			</div>

			<h3 className="spectra-gbs-nudge-modal__sublabel">{ __( 'Spacing', 'spectra-blocks' ) }</h3>
			<div className="spectra-gbs-nudge-modal__spacing">
				{ [ 8, 14, 22, 32, 44 ].map( ( s, i ) => (
					<span key={ i } className="spectra-gbs-nudge-modal__space" style={ { width: s, height: s } } />
				) ) }
			</div>
		</section>
	</div>
);

/**
 * Inert replica of the Pro Block CSS & JS editor flyout (tabbar + CSS/JS panels
 * + footer). Shown blurred behind the flyout upgrade card. aria-hidden.
 *
 * @return {Element} The faux CSS/JS editor shell.
 */
const FlyoutShellPreview = () => (
	<div className="spectra-gbs-nudge-flyout__shell" aria-hidden="true">
		<div className="spectra-gbs-nudge-flyout__tabbar">
			<span className="spectra-gbs-nudge-flyout__block-label">
				<SpectraIcon size={ 13 } />
				{ __( 'Container', 'spectra-blocks' ) }
			</span>
			<span className="spectra-gbs-nudge-flyout__token">
				<code>_current_block_</code>
				<span>{ __( 'this block', 'spectra-blocks' ) }</span>
			</span>
			<div className="spectra-gbs-nudge-flyout__tabs">
				<span className="spectra-gbs-nudge-flyout__tab is-active">{ __( 'Block', 'spectra-blocks' ) }</span>
				<span className="spectra-gbs-nudge-flyout__tab">.default-container</span>
				<span className="spectra-gbs-nudge-flyout__tab">.hero-card</span>
			</div>
		</div>
		<div className="spectra-gbs-nudge-flyout__panels">
			<div className="spectra-gbs-nudge-flyout__panel spectra-gbs-nudge-flyout__panel--css">
				<div className="spectra-gbs-nudge-flyout__panel-header">{ 'CSS' }</div>
				<pre className="spectra-gbs-nudge-flyout__code">
					<span className="tk-sel">._current_block_</span> {'{'}{'\n'}
					{'  '}<span className="tk-prop">display</span>: <span className="tk-val">flex</span>;{'\n'}
					{'  '}<span className="tk-prop">gap</span>: <span className="tk-num">24px</span>;{'\n'}
					{'  '}<span className="tk-prop">background</span>: <span className="tk-var">var(--spectra-surface)</span>;{'\n'}
					{'  '}<span className="tk-prop">border-radius</span>: <span className="tk-num">12px</span>;{'\n'}
					{'}'}
				</pre>
			</div>
			<div className="spectra-gbs-nudge-flyout__panel spectra-gbs-nudge-flyout__panel--js">
				<div className="spectra-gbs-nudge-flyout__panel-header">{ 'JS' }</div>
				<pre className="spectra-gbs-nudge-flyout__code">
					<span className="tk-com">{'// runs for this block on the front end'}</span>{'\n'}
					<span className="tk-kw">const</span> el = <span className="tk-fn">document</span>.<span className="tk-fn">querySelector</span>(<span className="tk-str">&apos;._current_block_&apos;</span>);{'\n'}
					el.<span className="tk-fn">addEventListener</span>(<span className="tk-str">&apos;click&apos;</span>, () =&gt; {'{'}{'\n'}
					{'  '}el.classList.<span className="tk-fn">toggle</span>(<span className="tk-str">&apos;is-open&apos;</span>);{'\n'}
					{'}'});
				</pre>
			</div>
		</div>
		<div className="spectra-gbs-nudge-flyout__footer">
			<span>{ __( 'Scoped to', 'spectra-blocks' ) }{ ' ' }<code>.spectra-blk-container</code></span>
			<span>{ __( 'Saves with the editor', 'spectra-blocks' ) }</span>
		</div>
	</div>
);

/**
 * Docked bottom flyout for the toolbar "Block CSS & JS" icon: blurred CSS/JS
 * editor preview with the white-label upgrade card on top.
 *
 * @return {Element} The flyout portal.
 */
const FlyoutView = () => {
	return createPortal(
		<div
			className="spectra-gbs-nudge-flyout"
			role="dialog"
			aria-label={ __( 'Block CSS & JS', 'spectra-blocks' ) }
		>
			<FlyoutShellPreview />
			<div className="spectra-gbs-nudge-flyout__overlay">
				<button
					type="button"
					className="spectra-gbs-nudge-flyout__close"
					aria-label={ __( 'Close', 'spectra-blocks' ) }
					onClick={ () => nudgeSingleton.close() }
				>
					×
				</button>
				<div className="spectra-gbs-nudge-flyout__card">
					<span className="spectra-gbs-nudge-flyout__lock">
						<LockIcon />
					</span>
					<h3 className="spectra-gbs-nudge-flyout__heading">
						{ __( 'Edit Block CSS & JS in Spectra Blocks Pro', 'spectra-blocks' ) }
					</h3>
					<p className="spectra-gbs-nudge-flyout__text">
						{ __(
							'Write CSS and JavaScript scoped to this block, with live preview and autocomplete. Available in Spectra Blocks Pro.',
							'spectra-blocks'
						) }
					</p>
					<UpgradeCta className="spectra-gbs-nudge-flyout__cta" />
				</div>
			</div>
		</div>,
		document.querySelector( '.interface-interface-skeleton__content' ) || document.body
	);
};

/**
 * Centered "Manage Global Styles" modal for the inspector button: backdrop
 * overlay + blurred GBS-manager shell + white-label upgrade card on top.
 *
 * @return {Element} The modal portal.
 */
const ModalView = () => {
	return createPortal(
		// eslint-disable-next-line jsx-a11y/no-noninteractive-element-interactions
		<div
			className="spectra-gbs-nudge-backdrop"
			role="dialog"
			aria-modal="true"
			aria-label={ __( 'Global Styles', 'spectra-blocks' ) }
			onMouseDown={ ( e ) => {
				if ( e.target === e.currentTarget ) {
					nudgeSingleton.close();
				}
			} }
		>
			<div className="spectra-gbs-nudge-modal">
				<div className="spectra-gbs-nudge-modal__body">
					<GBSManagerPreview />

					<div className="spectra-gbs-nudge-modal__overlay">
						<button
							type="button"
							className="spectra-gbs-nudge-modal__close"
							aria-label={ __( 'Close', 'spectra-blocks' ) }
							onClick={ () => nudgeSingleton.close() }
						>
							×
						</button>
						<div className="spectra-gbs-nudge-modal__card">
							<span className="spectra-gbs-nudge-modal__lock">
								<LockIcon />
							</span>
							<h3 className="spectra-gbs-nudge-modal__heading">
								{ __( 'Global Styles Available in', 'spectra-blocks' ) }{ ' ' }<span className="spectra-gbs-nudge-modal__heading-name">{ __( 'Spectra Blocks Pro', 'spectra-blocks' ) }</span>
							</h3>
							<p className="spectra-gbs-nudge-modal__cardtext">
								{ __(
									'Build your own design system inside WordPress. Generate design tokens from your brand, create your own variables, reusable classes and animations, and apply them across every block.',
									'spectra-blocks'
								) }
							</p>

							<UpgradeCta className="spectra-gbs-nudge-modal__cta" />
						</div>
					</div>
				</div>
			</div>
		</div>,
		document.body
	);
};

/**
 * Single always-mounted host. Renders the flyout or the modal depending on
 * which trigger fired; Escape closes either.
 *
 * @return {Element|null} The active view, or null when closed.
 */
const NudgeHost = () => {
	const [ variant, setVariant ] = useState( _nudgeVariant );

	useEffect( () => nudgeSingleton.subscribe( setVariant ), [] );

	useEffect( () => {
		if ( ! variant ) {
			return undefined;
		}
		const onKey = ( e ) => {
			if ( 'Escape' === e.key ) {
				nudgeSingleton.close();
			}
		};
		document.addEventListener( 'keydown', onKey );
		return () => document.removeEventListener( 'keydown', onKey );
	}, [ variant ] );

	if ( 'flyout' === variant ) {
		return <FlyoutView />;
	}
	if ( 'modal' === variant ) {
		return <ModalView />;
	}
	return null;
};

// ─── Toolbar button (per block) ─────────────────────────────────────────────────
const withGBSProNudge = createHigherOrderComponent( ( BlockEdit ) => {
	return ( props ) => {
		if ( isProActive() || ! isSupportedBlock( props.name ) ) {
			return <BlockEdit { ...props } />;
		}

		return (
			<>
				<BlockEdit { ...props } />
				<BlockControls>
					<ToolbarGroup>
						<ToolbarButton
							icon={ <SpectraIcon size={ 20 } /> }
							label={ __( 'Block CSS & JS', 'spectra-blocks' ) }
							onClick={ () => nudgeSingleton.toggleFlyout() }
							className="spectra-code-toolbar-btn"
						/>
					</ToolbarGroup>
				</BlockControls>
				<InspectorControls>
					<ToolsPanel
						label={ __( 'Global Styles', 'spectra-blocks' ) }
						className="spectra-manage-classes-inspector spectra-gbs-nudge-inspector"
						resetAll={ () => {} }
					>
						<ToolsPanelItem
							label={ __( 'Global Styles', 'spectra-blocks' ) }
							isShownByDefault
							hasValue={ () => false }
						>
						<p className="spectra-gbs-nudge-inspector__desc">
							{ __(
								'Apply reusable global classes and manage design tokens, CSS and JS across your blocks from one place.',
								'spectra-blocks'
							) }
						</p>
						<Button
							variant="secondary"
							className="spectra-gbs-nudge-inspector__btn"
							onClick={ () => nudgeSingleton.openModal() }
						>
							{ __( 'Manage Global Styles', 'spectra-blocks' ) }
						</Button>
						</ToolsPanelItem>
					</ToolsPanel>
				</InspectorControls>
			</>
		);
	};
}, 'withGBSProNudge' );

// Register the toolbar button and the single flyout host only when Pro is not
// active — installed-but-inactive and not-installed both get the nudge.
if ( ! isProActive() ) {
	// Priority 5 matches spectra-blocks-pro's own GS filter registration so the
	// "Global Styles" panel sits in the same inspector position with or without Pro.
	addFilter( 'editor.BlockEdit', 'spectra/gbs-pro-nudge', withGBSProNudge, 5 );
	registerPlugin( 'spectra-gbs-pro-nudge', { render: NudgeHost } );

	// Expose the nudge host so sibling extensions (e.g. the Zip AI page notice)
	// can open the upgrade modal directly — the same popup the inspector's
	// "Manage Global Styles" button opens. Only set when the nudge is live
	// (Pro inactive); when Pro is active, callers use the real GBS editor.
	window.__spectraGbsProNudge = nudgeSingleton;
}
