/**
 * CustomClassesPanel — create, edit, and delete gs-* utility classes.
 *
 * Classes are stored via POST /global-styles/custom-classes and CSS is
 * generated by the free engine's render_user_classes(). Once saved, a class
 * appears in the block inspector's "Global Styles" panel.
 *
 * Storage format per class:
 *   { default: { 'color': 'red', 'font-size': '1rem' },
 *     hover:   { 'opacity': '0.8' } }
 *
 * Legacy classes stored as a raw CSS string are automatically migrated to the
 * Default bucket when opened for editing.
 *
 * @since x.x.x
 */

/**
 * WordPress dependencies.
 */
import { useState, useCallback, useEffect, useRef, forwardRef, useImperativeHandle } from '@wordpress/element';
import { useSelect } from '@wordpress/data';
import { __, sprintf } from '@wordpress/i18n';
import { Spinner, TextControl, Icon } from '@wordpress/components';
import { edit as editIcon } from '@wordpress/icons';

/**
 * Internal dependencies.
 */
import { useCustomClasses } from '../../hooks/useCustomClasses.js';
import { regenerateEditorCSS, regeneratePageCSS } from '../../utils/liveVars.js';
import CSSAutocomplete from '../CSSAutocomplete.jsx';
import {
	textToBucket,
	getStoredBucketText,
} from '../../utils/bucketHelpers.js';

/** State buckets the user can add declarations to. */
const BUCKETS = [
	{ id: 'default', label: __( 'Default', 'spectra-blocks' ) },
	{ id: 'hover', label: __( 'Hover (:hover)', 'spectra-blocks' ) },
	{ id: 'focus', label: __( 'Focus (:focus)', 'spectra-blocks' ) },
	{ id: 'active', label: __( 'Active (:active)', 'spectra-blocks' ) },
	{ id: 'focus-within', label: __( 'Focus Within', 'spectra-blocks' ) },
	{ id: 'before', label: __( 'Before (::before)', 'spectra-blocks' ) },
	{ id: 'after', label: __( 'After (::after)', 'spectra-blocks' ) },
	{ id: 'md', label: __( 'Tablet (md)', 'spectra-blocks' ) },
	{ id: 'lg', label: __( 'Desktop (lg)', 'spectra-blocks' ) },
	{ id: 'md_hover', label: __( 'Tablet Hover', 'spectra-blocks' ) },
	{ id: 'lg_hover', label: __( 'Desktop Hover', 'spectra-blocks' ) },
];

/**
 * ClassEditor — inline editor for a single class's state buckets.
 *
 * @since x.x.x
 *
 * @param {Object}   props
 * @param {string}   props.className Class name (e.g. 'gs-hero').
 * @param {*}        props.styles    Current stored styles (object or legacy string).
 * @param {Function} props.onSave    Called with (className, styles).
 * @param {Function} props.onCancel  Called to close without saving.
 * @param {boolean}  props.saving    Whether save is in progress.
 * @return {Element} Rendered ClassEditor component.
 */
const ClassEditor = forwardRef( ( { className, styles, onSave, onCancel, saving }, ref ) => {
	const [ buckets, setBuckets ] = useState( () =>
		Object.fromEntries(
			BUCKETS.map( ( b ) => [
				b.id,
				getStoredBucketText( styles, b.id ),
			] )
		)
	);

	const [ originalBuckets ] = useState( () =>
		Object.fromEntries(
			BUCKETS.map( ( b ) => [ b.id, getStoredBucketText( styles, b.id ) ] )
		)
	);

	const isDirty = BUCKETS.some(
		( b ) => ( buckets[ b.id ] ?? '' ) !== ( originalBuckets[ b.id ] ?? '' )
	);

	const isLegacy = typeof styles === 'string' && styles.trim().length > 0;

	// Which state (bucket) is currently being edited / previewed.
	const [ activeState, setActiveState ] = useState( 'default' );

	const handleSave = () => {
		const compiled = {};
		BUCKETS.forEach( ( { id } ) => {
			const parsed = textToBucket( buckets[ id ] ?? '' );
			if ( Object.keys( parsed ).length ) {
				compiled[ id ] = parsed;
			}
		} );
		onSave( className, compiled );
	};

	useImperativeHandle( ref, () => ( { save: handleSave } ) );

	const activeMeta = BUCKETS.find( ( b ) => b.id === activeState ) ?? BUCKETS[ 0 ];
	const activeText = buckets[ activeState ] ?? '';
	const inputId = `spectra-cls-${ className.replace( /[^a-z0-9]/gi, '-' ) }-${ activeState }`;

	// Inline preview built from the *active* state's declarations and applied
	// to the sample element, so switching state updates the preview live.
	const previewStyle = Object.fromEntries(
		( activeText.match( /([^:;{}]+):([^;{}]+)/g ) ?? [] )
			.map( ( decl ) => {
				const [ , p, v ] = decl.match( /([^:]+):(.+)/ ) ?? [];
				if ( ! p || ! v ) {
					return [ '', '' ];
				}
				const prop = p.trim().replace( /-([a-z])/g, ( _, c ) => c.toUpperCase() );
				return [ prop, v.trim() ];
			} )
			.filter( ( [ p ] ) => p )
	);

	// When Pro is active it registers its CodeMirror CSS editor (line numbers +
	// dropdown autocomplete) on window.spectraGBS. Use it for parity with the
	// per-block flyout; otherwise fall back to the lightweight ghost-text editor.
	const InjectedCSSEditor =
		( typeof window !== 'undefined' && window.spectraGBS && window.spectraGBS.CSSCodeMirror ) || null;

	return (
		<div className="spectra-gbs-class-editor">
			<div className="spectra-gbs-class-editor__name">
				<code>.{ className }</code>
			</div>

			{ isLegacy && (
				<div className="spectra-gbs-custom-css__info">
					<p className="spectra-gbs-custom-css__info-text">
						{ __(
							'This class was created with raw CSS. The content has been placed in the Default state — review and save to convert to the new format.',
							'spectra-blocks'
						) }
					</p>
				</div>
			) }

			{ /* Toolbar — pick which state to edit */ }
			<div className="spectra-gbs-class-editor__toolbar">
				{ /* eslint-disable-next-line jsx-a11y/label-has-associated-control */ }
				<label className="spectra-gbs-class-editor__toolbar-label" htmlFor={ `${ inputId }-state` }>
					{ __( 'State', 'spectra-blocks' ) }
				</label>
				<select
					id={ `${ inputId }-state` }
					className="spectra-gbs-class-editor__state-select"
					value={ activeState }
					onChange={ ( e ) => setActiveState( e.target.value ) }
				>
					{ BUCKETS.map( ( { id, label } ) => {
						const hasContent = ( buckets[ id ] ?? '' ).trim().length > 0;
						return (
							<option key={ id } value={ id }>
								{ label }{ hasContent ? ' •' : '' }
							</option>
						);
					} ) }
				</select>
			</div>

			{ /* Split — code editor on the left, live preview on the right */ }
			<div className="spectra-gbs-class-editor__split">
				<div className="spectra-gbs-class-editor__code">
					{ InjectedCSSEditor ? (
						<InjectedCSSEditor
							key={ activeState }
							value={ activeText }
							onChange={ ( val ) =>
								setBuckets( ( prev ) => ( {
									...prev,
									[ activeState ]: val,
								} ) )
							}
							placeholder={ 'color: red;\nfont-size: 1rem;' }
							minHeight={ 180 }
							className="spectra-gbs-class-editor__cm"
							style={ { flex: 1, minWidth: 0 } }
						/>
					) : (
						<CSSAutocomplete
							id={ inputId }
							className="spectra-gbs-class-editor__textarea"
							value={ activeText }
							onChange={ ( e ) =>
								setBuckets( ( prev ) => ( {
									...prev,
									[ activeState ]: e.target.value,
								} ) )
							}
							placeholder="color: red;&#10;font-size: 1rem;"
							spellCheck={ false }
							rows={ 6 }
						/>
					) }
				</div>

				<div className="spectra-gbs-class-editor__preview-pane">
					<div className="spectra-gbs-class-editor__preview-head">
						<span>{ __( 'Live preview', 'spectra-blocks' ) }</span>
						<span className="spectra-gbs-class-editor__preview-state">{ activeMeta.label }</span>
					</div>
					<div className="spectra-gbs-class-editor__preview-body">
						<div className="spectra-gbs-class-editor__preview-sample" style={ previewStyle }>
							{ __( 'Aa — Sample block', 'spectra-blocks' ) }
						</div>
					</div>
				</div>
			</div>

			<div className="spectra-gbs-class-editor__actions">
				<button
					type="button"
					className="spectra-gbs-btn--secondary"
					onClick={ onCancel }
					disabled={ saving }
				>
					{ __( 'Cancel', 'spectra-blocks' ) }
				</button>
				<button
					type="button"
					className="spectra-gbs-btn--primary"
					onClick={ handleSave }
					disabled={ saving || ! isDirty }
				>
					{ saving ? __( 'Saving…', 'spectra-blocks' ) : __( 'Save', 'spectra-blocks' ) }
				</button>
			</div>
		</div>
	);
} );

/**
 * CustomClassesPanel component.
 *
 * @since x.x.x
 *
 * @param {Object}      props                Component props.
 * @param {string|null} props.initialClass   Class name to open for editing on mount (e.g. from flyout).
 * @param {Function}    props.onStatusChange Callback invoked when the panel's save/dirty status changes.
 * @return {Element} Rendered CustomClassesPanel.
 */
const CustomClassesPanel = ( { initialClass = null, onStatusChange } ) => {
	const postId = useSelect(
		( select ) => select( 'core/editor' )?.getCurrentPostId?.() ?? 0,
		[]
	);
	const { classes, loading, saving, saveClass, deleteClass } =
		useCustomClasses( null, postId );

	useEffect( () => {
		onStatusChange?.( { saving, previewing: false, dirty: false } );
	}, [ saving ] ); // eslint-disable-line react-hooks/exhaustive-deps
	const [ editing, setEditing ] = useState( null );
	const [ newName, setNewName ] = useState( '' );
	const [ nameError, setNameError ] = useState( '' );
	const [ confirmDelete, setConfirmDelete ] = useState( null );
	const [ initialActed, setInitialActed ] = useState( false );
	const [ searchQuery, setSearchQuery ] = useState( '' );
	const classEditorRef = useRef( null );


	// Auto-open the class editor when initialClass is provided (e.g. from flyout).
	useEffect( () => {
		if ( initialActed || loading || ! initialClass ) {
			return;
		}
		if ( classes[ initialClass ] !== undefined ) {
			setEditing( initialClass );
		}
		setInitialActed( true );
	}, [ initialActed, loading, initialClass, classes ] ); // eslint-disable-line react-hooks/exhaustive-deps

	const handleAdd = useCallback( () => {
		const trimmed = newName.trim().replace( /^gs-/, '' );
		if ( ! trimmed ) {
			setNameError( __( 'Enter a name.', 'spectra-blocks' ) );
			return;
		}
		if ( ! /^[a-z][a-z0-9-]*$/.test( trimmed ) ) {
			setNameError(
				__(
					'Use lowercase letters, digits and hyphens only.',
					'spectra-blocks'
				)
			);
			return;
		}
		const finalName = `gs-${ trimmed }`;
		if ( classes[ finalName ] !== undefined ) {
			setNameError(
				__( 'A class with this name already exists.', 'spectra-blocks' )
			);
			return;
		}
		setNameError( '' );
		setNewName( '' );
		setEditing( finalName );
	}, [ newName, classes ] );

	const handleSave = useCallback(
		async ( className, styles ) => {
			await saveClass( className, styles );
			setEditing( null );
			regenerateEditorCSS();
			regeneratePageCSS( postId );
		},
		[ saveClass, postId ]
	);

	const handleDelete = useCallback(
		async ( className ) => {
			await deleteClass( className );
			setConfirmDelete( null );
			if ( editing === className ) {
				setEditing( null );
			}
			regenerateEditorCSS();
			regeneratePageCSS( postId );
		},
		[ deleteClass, editing, postId ]
	);

	if ( loading ) {
		return (
			<div className="spectra-gbs-panel__loading">
				<Spinner />
				<span>{ __( 'Loading classes…', 'spectra-blocks' ) }</span>
			</div>
		);
	}

	const classNames = Object.keys( classes );
	const isNewClass = editing !== null && classes[ editing ] === undefined;

	const filteredClassNames = searchQuery.trim()
		? classNames.filter( ( name ) =>
			name.toLowerCase().includes( searchQuery.toLowerCase() )
		)
		: classNames;

	/* translators: %d: number of custom classes */
	const classCountLabel = sprintf(
		// eslint-disable-next-line @wordpress/i18n-translator-comments
		__( '%d class(es)', 'spectra-blocks' ),
		classNames.length
	);

	return (
		<div className="spectra-gbs-colors-panel">
			<div className="spectra-gbs-colors-panel__content">
				<div className="spectra-gbs-section spectra-gbs-section--classes">

					{ /* Toolbar: create + search side by side */ }
					<div className="spectra-gbs-class-toolbar">
						<div className="spectra-gbs-class-new">
							<span className="spectra-gbs-class-new__prefix">
								gs-
							</span>
							<TextControl
								className="spectra-gbs-class-new__input"
								value={ newName }
								onChange={ ( v ) => {
									setNewName( v );
									setNameError( '' );
								} }
								placeholder="hero-section"
								onKeyDown={ ( e ) => {
									if ( e.key === 'Enter' ) {
										handleAdd();
									}
								} }
								__nextHasNoMarginBottom
							/>
							<button
								type="button"
								className="spectra-gbs-btn--primary"
								onClick={ handleAdd }
								disabled={ saving || ! newName.trim() }
							>
								{ __( 'Create', 'spectra-blocks' ) }
							</button>
						</div>

						{ classNames.length > 0 && (
							<div className="spectra-gbs-class-search">
								<span className="spectra-gbs-class-search__icon" aria-hidden="true">
									<svg width="13" height="13" viewBox="0 0 14 14" fill="none">
										<circle cx="6" cy="6" r="4.5" stroke="currentColor" strokeWidth="1.2" />
										<path d="M9.5 9.5L12.5 12.5" stroke="currentColor" strokeWidth="1.2" strokeLinecap="round" />
									</svg>
								</span>
								<input
									className="spectra-gbs-class-search__input"
									type="search"
									placeholder={ __( 'Search…', 'spectra-blocks' ) }
									value={ searchQuery }
									onChange={ ( e ) => setSearchQuery( e.target.value ) }
									aria-label={ __( 'Search custom classes', 'spectra-blocks' ) }
								/>
								{ searchQuery && (
									<span className="spectra-gbs-class-search__count">
										{ filteredClassNames.length }/{ classNames.length }
									</span>
								) }
							</div>
						) }
					</div>

					{ nameError && (
						<p className="spectra-gbs-class-new__error">
							{ nameError }
						</p>
					) }

					{ /* Inline editor for a brand-new (unsaved) class */ }
					{ isNewClass && (
						<div className="spectra-gbs-section__field">
							<p className="spectra-gbs-section__label">
								{ __( 'New class', 'spectra-blocks' ) }
							</p>
							<div className="spectra-gbs-class-list">
								<div className="spectra-gbs-class-row is-editing">
									<ClassEditor
										ref={ classEditorRef }
										className={ editing }
										styles={ {} }
										onSave={ handleSave }
										onCancel={ () => setEditing( null ) }
										saving={ saving }
									/>
								</div>
							</div>
						</div>
					) }

					{ /* Existing classes */ }
					{ filteredClassNames.length > 0 && (
						<div className="spectra-gbs-section__field">
							{ ! searchQuery && (
								<p className="spectra-gbs-section__label">
									{ classCountLabel }
								</p>
							) }
							<div className="spectra-gbs-class-list">
								{ filteredClassNames.map( ( name ) => {
									const stored = classes[ name ];
									const styleCount = ( () => {
										if ( typeof stored === 'string' ) {
											return stored.trim() ? 1 : 0;
										}
										return Object.keys(
											stored ?? {}
										).reduce( ( acc, bucket ) => {
											const b = stored[ bucket ];
											return (
												acc +
												( Array.isArray( b )
													? b.length
													: Object.keys( b ).length )
											);
										}, 0 );
									} )();

									/* translators: %d: number of CSS declarations */
									const countLabel = sprintf(
										// eslint-disable-next-line @wordpress/i18n-translator-comments
										__(
											'%d declarations',
											'spectra-blocks'
										),
										styleCount
									);

									return (
										<div
											key={ name }
											className={ `spectra-gbs-class-row${
												editing === name
													? ' is-editing'
													: ''
											}` }
										>
											{ editing === name ? (
												<ClassEditor
													ref={ classEditorRef }
													className={ name }
													styles={ stored }
													onSave={ handleSave }
													onCancel={ () =>
														setEditing( null )
													}
													saving={ saving }
												/>
											) : (
												<>
													<code className="spectra-gbs-class-row__name">
														.{ name }
													</code>
													<span className="spectra-gbs-class-row__count">
														{ countLabel }
													</span>
													<div className="spectra-gbs-class-row__actions">
														<button
															className="spectra-gbs-class-row__btn"
															onClick={ () =>
																setEditing(
																	name
																)
															}
															title={ __(
																'Edit',
																'spectra-blocks'
															) }
														>
															<Icon icon={ editIcon } size={ 16 } />
														</button>
														{ confirmDelete ===
														name ? (
															<>
																<button
																	className="spectra-gbs-class-row__btn is-danger"
																	onClick={ () =>
																		handleDelete(
																			name
																		)
																	}
																	disabled={
																		saving
																	}
																>
																	{ __(
																		'Confirm',
																		'spectra-blocks'
																	) }
																</button>
																<button
																	className="spectra-gbs-class-row__btn"
																	onClick={ () =>
																		setConfirmDelete(
																			null
																		)
																	}
																>
																	{ __(
																		'Cancel',
																		'spectra-blocks'
																	) }
																</button>
															</>
														) : (
															<button
																className="spectra-gbs-class-row__btn is-danger"
																onClick={ () =>
																	setConfirmDelete(
																		name
																	)
																}
																title={ __(
																	'Delete',
																	'spectra-blocks'
																) }
															>
																✕
															</button>
														) }
													</div>
												</>
											) }
										</div>
									);
								} ) }
							</div>
						</div>
					) }

					{ /* Empty state — no classes at all */ }
					{ classNames.length === 0 && ! editing && (
						<div className="spectra-gbs-section__empty">
							{ __(
								'No custom classes yet. Create one above.',
								'spectra-blocks'
							) }
						</div>
					) }

					{ /* No search results */ }
					{ classNames.length > 0 && filteredClassNames.length === 0 && (
						<div className="spectra-gbs-section__empty">
							{ __( 'No classes match your search.', 'spectra-blocks' ) }
						</div>
					) }

				</div>
			</div>
		</div>
	);
};

export default CustomClassesPanel;
